name: Push Build
on: [push]
jobs:
  
  build-windows-32:
    name: Build Windows 32
    runs-on: [windows-latest]
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Install GCC
        run: choco install mingw --force --force-dependencies
        
      - name: Download Go 1.13.7-win32
        uses: DuckSoft/setup-go-win32@v999
        with:
          go-version: 1.13
        
      - name: Compile
        shell: cmd
        run: |
          set GOARCH=386
          set GOOS=windows
          set CGO_ENABLED=1
          go env
          go build -buildmode=c-archive -ldflags "-s -w" -o build\libqvb-32.a main.go

      - name: Upload Windows 32bit
        uses: actions/upload-artifact@master
        with:
          name: libqvb-win32.a
          path: build/libqvb-32.a

  build-windows-64:
    name: Build Windows 64
    runs-on: [windows-latest]
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
      
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      
    - name: Checkout dependencies from cache
      id: cache
      uses: actions/cache@v1.1.0
      with:
        path: ./vendor
        key: ${{ runner.os }}-vendor

    - name: Get dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        go get -v -t -d ./...

    - name: Build Windows 64bit
      shell: cmd
      run: |
        go build -buildmode=c-archive -ldflags "-s -w" -o build\libqvb-64.a main.go

    - name: Upload Windows 64bit
      uses: actions/upload-artifact@master
      with:
        name: libqvb-win64.a
        path: build/libqvb-64.a

  build-macOS:
    name: Build macOS
    runs-on: [macos-latest]
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
      
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Checkout dependencies from cache
      id: cache
      uses: actions/cache@v1.1.0
      with:
        path: ./vendor
        key: ${{ runner.os }}-vendor

    - name: Get dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        go get -v -t -d ./...

    - name: Build
      run: chmod +x ./build.sh && ./build.sh
    
    - name: Upload macOS Build
      uses: actions/upload-artifact@master
      with:
        name: libqvb-darwin.a
        path: build/libqvb.a

  build-linux:
    name: Build Linux
    runs-on: [ubuntu-latest]
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Checkout dependencies from cache
      id: cache
      uses: actions/cache@v1.1.0
      with:
        path: ./vendor
        key: ${{ runner.os }}-vendor

    - name: Get dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        go get -v -t -d ./...

    - name: Build
      run: chmod +x ./build.sh && ./build.sh
      
    - name: Upload Linux Build
      uses: actions/upload-artifact@master
      with:
        name: libqvb-linux64.a
        path: build/libqvb.a
